---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - vim
      - htop
    state: present
