pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build PHP Application'
            }
        }

        stage('Test') {
            steps {
                echo 'Run Tests'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy Application'
            }
        }

    }

}
