@Library('shared-library') _

pipeline {

    agent any

    parameters {

        choice(
            name: 'ENVIRONMENT',
            choices: [
                'dev',
                'qa',
                'prod'
            ]
        )

    }

    stages {

        stage('Build') {
            steps {
                buildPhp()
            }
        }

        stage('Deploy') {
            steps {
                deployApp(params.ENVIRONMENT)
            }
        }

    }
}
