name: Application Validation

on:
  push:
    paths:
      - 'app/**'

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Verify Files
        run: |
          ls -la app
