name: Docker Validation

on:
  push:
    paths:
      - "docker-compose.yml"
      - "app/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build Containers
        run: docker compose build
